CREATE TABLE todos
(
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE               TEXT NOT NULL UNIQUE,
    COMPLETED           BOOLEAN NOT NULL DEFAULT FALSE,
    MODIFICATION_DATE   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATION_DATE       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);